### ISSUE TITLE
Does not build on 6.12.20

### ISSUE THREAD

**Issue by mark-herbert42** [hamadmarri/ECHO-CPU-Scheduler#11]
Compiles well - but does not build and stops on ld phase

  DESCEND objtool
  CALL    scripts/checksyscalls.sh
  INSTALL libsubcmd_headers
  UPD     include/generated/utsversion.h
  CC      init/version-timestamp.o
  LD      vmlinux
ld: kernel/sched/bs.o: in function `sched_balance_trigger':
bs.c:(.text+0x2e71): undefined reference to `arch_asym_cpu_priority'
ld: bs.c:(.text+0x2e7b): undefined reference to `arch_asym_cpu_priority'
ld: kernel/sched/build_utility.o: in function `build_sched_domains':
build_utility.c:(.text+0x5b1b): undefined reference to `arch_asym_cpu_priority'
ld: build_utility.c:(.text+0x5b27): undefined reference to `arch_asym_cpu_priority'
make[2]: *** [scripts/Makefile.vmlinux:34: vmlinux] Error 1
make[1]: *** [/var/tmp/linux-6.12.20/Makefile:1179: vmlinux] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:224: __sub-make] Error 2

[config.txt](https://github.com/user-attachments/files/19485728/config.txt)

**Comment by hamadmarri** [comment]
Hello @mark-herbert42 

It compiled with me fine. for v6.12.20 Please try `make distclean && make clean`
Please try with this config attached.

[.config.txt](https://github.com/user-attachments/files/19514231/default.config.txt)

**Comment by mark-herbert42** [comment]
Located the missing config - this function is located in itmt.c file which is compiled only if CONFIG_SCHED_MC and  CONFIG_SCHED_MC_PRIO is set to true.

So I guess it would be good idea to make those options forced by enabling  ECHO scheduler

**Comment by hamadmarri** [comment]
The echo patch doesn't change itmt.c
I suggest to make a new clean build
