### ISSUE TITLE
6.12.19 Compilation fails on Arch

### ISSUE THREAD

**Issue by NotMithical** [hamadmarri/ECHO-CPU-Scheduler#10]
Trying to build 6.12.19 using Arch's default linux-lts PKGBUILD with `linux-6.12-echo.patch`. Patch applies cleanly, but I get the following errors:

```
kernel/sched/bs.c: In function ‘init_sched_fair_class’:
kernel/sched/bs.c:894:37: error: ‘sched_balance_softirq’ undeclared (first use in this function); did you mean ‘sched_balance_trigger’?
  894 |         open_softirq(SCHED_SOFTIRQ, sched_balance_softirq);
      |                                     ^~~~~~~~~~~~~~~~~~~~~
      |                                     sched_balance_trigger
kernel/sched/bs.c:894:37: note: each undeclared identifier is reported only once for each function it appears in
In file included from kernel/sched/bs.c:769:
kernel/sched/balancer.h: At top level:
kernel/sched/balancer.h:844:13: warning: ‘nohz_balancer_kick’ used but never defined
  844 | static void nohz_balancer_kick(struct rq *rq);
      |             ^~~~~~~~~~~~~~~~~~
kernel/sched/balancer.h:542:13: warning: ‘idle_balance’ defined but not used [-Wunused-function]
  542 | static void idle_balance(struct rq *this_rq)
      |             ^~~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:229: kernel/sched/bs.o] Error 1
make[3]: *** [scripts/Makefile.build:478: kernel/sched] Error 2
make[2]: *** [scripts/Makefile.build:478: kernel] Error 2
make[2]: *** Waiting for unfinished jobs....

```

**Comment by hamadmarri** [comment]
Hello @NotMithical 

Could you please attach the .config file
What "6.12.19 Arch's default linux-lts" git/repo you applied the patch on?
I want to try the patch on the same repo. Please provide the url or the method to fetch the same kernel code 

Thank you

**Comment by NotMithical** [comment]
[config.txt](https://github.com/user-attachments/files/19394523/config.txt)

The PKGBUILD uses the latest longterm tarball from kernel.org. The PKGBUILD and the additional patches it applies are in this repo: https://gitlab.archlinux.org/archlinux/packaging/packages/linux-lts

Please let me know if I missed anything. I've only successfully compiled the kernel a few times, so I'm still figuring things out.

**Comment by hamadmarri** [comment]
`CONFIG_NO_HZ_FULL=y`

Nohz full is not supported, try with nohz idle

**Comment by NotMithical** [comment]
That took care of it. Thank you!
