### ISSUE TITLE
Failed to compile on 6.12.38

### ISSUE THREAD

**Issue by CloudPassenger** [hamadmarri/ECHO-CPU-Scheduler#12]
Dear developer,

when I try to apply the patch to Linux kernel 6.12.38. It failed with these errors

```
In file included from kernel/sched/bs.c:47:
kernel/sched/fair_numa.h: In function ‘update_numa_stats’:
kernel/sched/fair_numa.h:746:43: error: ‘struct cfs_rq’ has no member named ‘h_nr_running’; did you mean ‘nr_running’?
  746 |                 ns->nr_running += rq->cfs.h_nr_running;
      |                                           ^~~~~~~~~~~~
      |                                           nr_running
In file included from kernel/sched/bs.c:49:
kernel/sched/fair_dep_funcs.h: In function ‘hrtick_start_fair’:
kernel/sched/fair_dep_funcs.h:481:21: error: ‘struct cfs_rq’ has no member named ‘h_nr_running’; did you mean ‘nr_running’?
  481 |         if (rq->cfs.h_nr_running > 1) {
      |                     ^~~~~~~~~~~~
      |                     nr_running
kernel/sched/bs.c: In function ‘enqueue_task_fair’:
kernel/sched/bs.c:342:25: error: ‘struct cfs_rq’ has no member named ‘h_nr_running’; did you mean ‘nr_running’?
  342 |                 cfs_rq->h_nr_running++;
      |                         ^~~~~~~~~~~~
      |                         nr_running
kernel/sched/bs.c: In function ‘dequeue_task_fair’:
kernel/sched/bs.c:371:17: error: ‘struct cfs_rq’ has no member named ‘h_nr_running’; did you mean ‘nr_running’?
  371 |         cfs_rq->h_nr_running--;
      |                 ^~~~~~~~~~~~
      |                 nr_running
In file included from kernel/sched/bs.c:769:
kernel/sched/balancer.h: In function ‘newidle_balance’:
kernel/sched/balancer.h:774:26: error: ‘struct cfs_rq’ has no member named ‘h_nr_running’; did you mean ‘nr_running’?
  774 |         if (this_rq->cfs.h_nr_running && !pulled_task)
      |                          ^~~~~~~~~~~~
      |                          nr_running
kernel/sched/balancer.h:778:49: error: ‘struct cfs_rq’ has no member named ‘h_nr_running’; did you mean ‘nr_running’?
  778 |         if (this_rq->nr_running != this_rq->cfs.h_nr_running)
      |                                                 ^~~~~~~~~~~~
      |                                                 nr_running
In file included from kernel/sched/balancer.h:866:
kernel/sched/nohz.h: In function ‘nohz_balancer_kick’:
kernel/sched/nohz.h:456:29: error: ‘struct cfs_rq’ has no member named ‘h_nr_running’; did you mean ‘nr_running’?
  456 |                 if (rq->cfs.h_nr_running >= 1 && check_cpu_capacity(rq, sd)) {
      |                             ^~~~~~~~~~~~
      |                             nr_running
make[7]: *** [scripts/Makefile.build:234: kernel/sched/bs.o] Error 1
make[6]: *** [scripts/Makefile.build:483: kernel/sched] Error 2
```

I run it via Github Actions. Could you please have a look on my workflow runs? Thanks a lot!

https://github.com/CloudPassenger/Cloud-Kernel-BBRv3/actions/runs/16724677421/job/47337095753

**Comment by hamadmarri** [comment]
Could you please try the patch with kernel version "Linux 6.12.18". This is the one I patch echo to. I just want to check if the issue is related to v6.12.38 or something else.

Thank you
